// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using puzzle.backend.coding.callenge.NETCore.Infraestructure.DataContext;

#nullable disable

namespace puzzle.backend.coding.callenge.NETCore.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("puzzle.backend.coding.callenge.NETCore.Domain.Aggregates.BookinAgg.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int?>("FurnitureId")
                        .HasColumnType("int");

                    b.Property<string>("RentalDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookingId");

                    b.HasIndex("ClientId");

                    b.HasIndex("EventId");

                    b.HasIndex("FurnitureId");

                    b.ToTable("Booking");
                });

            modelBuilder.Entity("puzzle.backend.coding.callenge.NETCore.Domain.Aggregates.ClientAgg.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("ClientId");

                    b.HasIndex("StatusId");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("puzzle.backend.coding.callenge.NETCore.Domain.Aggregates.EventAgg.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RentalFee")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("EventId");

                    b.ToTable("Event");
                });

            modelBuilder.Entity("puzzle.backend.coding.callenge.NETCore.Domain.Aggregates.FurnitureAgg.Furniture", b =>
                {
                    b.Property<int>("FurnitureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FurnitureId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RentalFee")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("FurnitureId");

                    b.ToTable("Furniture");
                });

            modelBuilder.Entity("puzzle.backend.coding.callenge.NETCore.Domain.Aggregates.StatusAgg.Status", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatusId");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("puzzle.backend.coding.callenge.NETCore.Domain.Aggregates.BookinAgg.Booking", b =>
                {
                    b.HasOne("puzzle.backend.coding.callenge.NETCore.Domain.Aggregates.ClientAgg.Client", "Client")
                        .WithMany("Bookings")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("puzzle.backend.coding.callenge.NETCore.Domain.Aggregates.EventAgg.Event", "Event")
                        .WithMany("Bookings")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("puzzle.backend.coding.callenge.NETCore.Domain.Aggregates.FurnitureAgg.Furniture", null)
                        .WithMany("Bookings")
                        .HasForeignKey("FurnitureId");

                    b.Navigation("Client");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("puzzle.backend.coding.callenge.NETCore.Domain.Aggregates.ClientAgg.Client", b =>
                {
                    b.HasOne("puzzle.backend.coding.callenge.NETCore.Domain.Aggregates.StatusAgg.Status", "Status")
                        .WithMany("Clients")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("puzzle.backend.coding.callenge.NETCore.Domain.Aggregates.ClientAgg.Client", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("puzzle.backend.coding.callenge.NETCore.Domain.Aggregates.EventAgg.Event", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("puzzle.backend.coding.callenge.NETCore.Domain.Aggregates.FurnitureAgg.Furniture", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("puzzle.backend.coding.callenge.NETCore.Domain.Aggregates.StatusAgg.Status", b =>
                {
                    b.Navigation("Clients");
                });
#pragma warning restore 612, 618
        }
    }
}
